apiVersion: v1
kind: Service
metadata:
  name: backend-api-svc
  namespace: NAMESPACE
spec:
  selector:
    app: marsel-demo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marsel-demo-api
  namespace: NAMESPACE
  labels:
    app: marsel-demo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marsel-demo-api
  template:
    metadata:
      labels:
        app: marsel-demo-api
    spec:
      containers:
      - name: marsel-demo-api
        image: 401413892014.dkr.ecr.us-east-1.amazonaws.com/apiapp:IMAGEVERSION
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-endpoint
