apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: NAMESPACE
type: Opaque
data:
  db-endpoint: cG9zdGdyZXM6Ly9hZG1pbjpiODRuZGRmdzByMzRobEByZHMtcG9zdGdyZXMtY2x1c3Rlci1mdmZkZGYuYW1hem9uYXdzLmNvbS9leGNoYW5nZWRi
